apiVersion: batch/v1
kind: CronJob
metadata:
  name: garmin-fit-to-shp
  namespace: garmin-fit
spec:
  # Run every 2 hours
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: app
              image: franchyze923/garmin-fit-downloader:2.0
              imagePullPolicy: IfNotPresent
              args:
                - "--since-days"
                - "30"
                - "--fit-dir"
                - "/data/garmin_fits"
                - "--token-dir"
                - "/data/.garminconnect"
              envFrom:
                - secretRef:
                    name: garmin-connect-credentials
              volumeMounts:
                - name: data
                  mountPath: /data
              resources:
                requests:
                  cpu: "100m"
                  memory: "512Mi"
                limits:
                  cpu: "1"
                  memory: "1Gi"
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: garmin-fit-nfs
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-fit-nfs
  namespace: garmin-fit
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
