apiVersion: v1
kind: Namespace
metadata:
  name: hello-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hello-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          args: ["/bin/sh","-c","echo 'Hello from A' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: hello-a
  annotations:
    io.cilium/lb-ipam-sharing-key: "apps"
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 8083
      targetPort: 80
