apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-c
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://192.168.40.86/frans-project/hello-c
    chart: hello-c
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - ../../values/hello-c/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true