apiVersion: v1
kind: Namespace
metadata:
  name: hello-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hello-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          args: ["/bin/sh","-c","echo 'Hello from B' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: hello-b
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
